<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Helvetica:wght@400;700&display=swap" />
    <link rel="stylesheet" href="index.css" />
    <link rel="stylesheet" href="../home/nav.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/hmac-sha256.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/enc-base64.min.js"></script>

  </head>
  <body>
  <?php include "../home/nav.php" ?>
    <div class="main-container">
      <div class="frame-8">
        <div class="frame-9">
          <div class="frame-a">
            <div class="frame-b" id="basic">
              <div class="frame-c">
                <div class="frame-d">
                  <div class="frame-e">
                    <span class="starter">Starter</span
                    ><span class="affordable-pricing-specific"
                      >Affordable Pricing , Specific Features
                    </span>
                  </div>
                  <div class="frame-f">
                    <div class="rs-month">
                      <span class="rs">Rs. 299 /</span
                      ><span class="month">month</span>
                    </div>
                  </div>
                  <div class="frame-10">
                    <div class="frame-11">
                      <span class="plan-includes">This plan Includes :</span>
                    </div>
                    <div class="frame-12">
                      <div class="frame-13">
                        <div class="tick"><div class="vector-14"></div></div>
                        <span class="unlimited-invoice-creation"
                          >Unlimited Invoice Creation</span
                        >
                      </div>
                      <div class="frame-15">
                        <div class="tick-16"><div class="vector-17"></div></div>
                        <span class="unlimited-downloads"
                          >Unlimited Downloads</span
                        >
                      </div>
                      <div class="frame-18">
                        <div class="tick-19"><div class="vector-1a"></div></div>
                        <span class="edit-update-manage-invoices"
                          >Edit , Update and manage invoices</span
                        >
                      </div>
                      <div class="frame-1b">
                        <div class="tick-1c"><div class="vector-1d"></div></div>
                        <span class="free-7-days-trial"
                          >Get Free 7 Days Trial</span
                        >
                      </div>
                    </div>
                  </div>
                </div>
                <div class="frame-1e" data-package="Starter" data-amount="299">
                  <button class="button-1f">
                    <div class="pngegg"></div>
                    <span class="pay-with-esewa">Pay with Esewa</span></button
                  ><button class="button-khalti" data-package="Starter" data-amount="299" >
                    <div class="pngfind-wallet-png"></div>
                    <span class="pay-with-khalti">Pay with Khalti</span>
                  </button>
                </div>
              </div>
            </div>
            <div class="frame-21"id="standard">
              <div class="frame-22" >
                <div class="frame-23">
                  <div class="frame-24">
                    <span class="premium">Premium</span
                    ><span class="affordable-pricing-unlimited"
                      >Affordable Pricing , Unlimited Features
                    </span>
                  </div>
                  <div class="frame-25">
                    <div class="rs-per-month">
                      <span class="rs-499-per">Rs. 499 /</span
                      ><span class="month-26">month</span>
                    </div>
                  </div>
                  <div class="frame-27">
                    <div class="frame-28">
                      <span class="this-plan-includes"
                        >This plan Includes :</span
                      >
                    </div>
                    <div class="frame-29">
                      <div class="frame-2a">
                        <div class="tick-2b"><div class="vector-2c"></div></div>
                        <span class="unlimited-invoice-creation-2d"
                          >Unlimited Invoice Creation</span
                        >
                      </div>
                      <div class="frame-2e">
                        <div class="tick-2f"><div class="vector-30"></div></div>
                        <span class="unlimited-downloads-31"
                          >Unlimited Downloads</span
                        >
                      </div>
                      <div class="frame-32">
                        <div class="tick-33"><div class="vector-34"></div></div>
                        <span class="edit-update-manage"
                          >Edit , Update and manage invoices</span
                        >
                      </div>
                      <div class="frame-35">
                        <div class="tick-36"><div class="vector-37"></div></div>
                        <span class="get-easy-payment"
                          >Get Easy Payment Solution</span
                        >
                      </div>
                      <div class="frame-38">
                        <div class="tick-39"><div class="vector-3a"></div></div>
                        <span class="auto-mail-sending"
                          >Auto mail sending Feature</span
                        >
                      </div>
                      <div class="frame-3b">
                        <div class="tick-3c"><div class="vector-3d"></div></div>
                        <span class="other-file-format"
                          >Other File format download option</span
                        >
                      </div>
                    </div>
                  </div>
                </div>
                <div class="frame-3e">
                  <button class="frame-3f" data-package="Premium" data-amount="499">
                    <div class="pngegg-40"></div>
                    <span class="pay-with-esewa-41"
                      >Pay with Esewa</span
                    ></button
                  ><button class="button-khalti" data-package="Premium" data-amount="499">
                    <div class="pngfind-wallet"></div>
                    <span class="pay-with-khalti-43">Pay with Khalti</span>
                  </button>
                </div>
              </div>
            </div>
            <div class="frame-44" id="premium">
              <div class="frame-45">
                <div class="frame-46">
                  <div class="frame-47">
                    <span class="saver-deal">Saver Deal</span
                    ><span class="affordable-pricing-unlimited-48"
                      >Affordable Pricing , Unlimited Saving Deal</span
                    >
                  </div>
                  <div class="frame-49">
                    <div class="frame-4a">
                      <span class="rs-year">Rs. 2599 /</span
                      ><span class="year">year</span>
                    </div>
                  </div>
                  <div class="frame-4b">
                    <div class="frame-4c">
                      <span class="this-plan-includes-4d"
                        >This plan Includes :</span
                      >
                    </div>
                    <div class="frame-4e">
                      <div class="frame-4f">
                        <div class="tick-50"><div class="vector-51"></div></div>
                        <span class="unlimited-invoice-creation-52"
                          >Unlimited Invoice Creation</span
                        >
                      </div>
                      <div class="frame-53">
                        <div class="tick-54"><div class="vector-55"></div></div>
                        <span class="unlimited-downloads-56"
                          >Unlimited Downloads</span
                        >
                      </div>
                      <div class="frame-57">
                        <div class="tick-58"><div class="vector-59"></div></div>
                        <span class="edit-update-manage-5a"
                          >Edit , Update and manage invoices</span
                        >
                      </div>
                      <div class="frame-5b">
                        <div class="tick-5c"><div class="vector-5d"></div></div>
                        <span class="easy-payment-solution"
                          >Get Easy Payment Solution</span
                        >
                      </div>
                      <div class="frame-5e">
                        <div class="tick-5f"><div class="vector-60"></div></div>
                        <span class="auto-mail-sending-61"
                          >Auto mail sending Feature</span
                        >
                      </div>
                      <div class="frame-62">
                        <div class="tick-63"><div class="vector-64"></div></div>
                        <span class="file-format-download"
                          >Other File format download option</span
                        >
                      </div>
                    </div>
                  </div>
                </div>
                <div class="frame-65">
                  <button class="button-66">
                    <div class="pngegg-67"></div>
                    <span class="pay-with-esewa-68"
                      >Pay with Esewa</span
                    ></button
                  ><button class="button-khalti"data-package="Saver" data-amount="2599">
                    <div class="pngfind-wallet-6a"></div>
                    <span class="pay-with-khalti-6b">Pay with Khalti</span>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
<script src="../myjs/eventHandling.js" ></script>
  </body>
</html>
