<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Generated by Codia AI</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Helvetica:wght@400;700&display=swap" />
  <link rel="stylesheet" href="index.css" />
  <link rel="stylesheet" href="../home/nav.css" />

</head>

<body>
  <div class="main-container">
    <?php include "../home/nav.php" ?>
    <div class="frame-7">
      <div class="frame-8">
        <div class="frame-9">
          <div class="frame-a">
            <div class="frame-b">
              <span class="current-plan">Current Plan : </span><span class="free-plan"><?php echo htmlspecialchars($planInfo); ?></span>
            </div>
            <div class="frame-c">
              <span class="my-profile">My Profile</span><span class="hi-manjish">Hi <?php echo htmlspecialchars($fullName); ?> , How are you doing !</span>
            </div>
          </div>
          <div class="frame-d">
            <div class="frame-e">
              <div class="frame-f">
                <div class="frame-10">
                  <input class="frame-input" />
                  <div class="frame-11">
                    <div class="frame-12">
                      <div class="frame-13">
                        <div class="user-square"></div>
                      </div>
                      <div class="frame-14">
                        <span class="manjish-upadhaya"><?php echo htmlspecialchars($fullName); ?></span>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="frame-15">
                  <input class="frame-input-16" />
                  <div class="frame-17">
                    <div class="mail"></div>
                  </div>
                  <div class="frame-18">
                    <span class="manjishupadhaya-email"><?php echo htmlspecialchars($email); ?></span>
                  </div>
                </div>
                <div class="frame-19">
                  <input class="frame-input-1a" />
                  <div class="frame-1b">
                    <div class="frame-1c">
                      <div class="frame-1d">
                        <div class="whatsapp-business"></div>
                      </div>
                      <div class="frame-1e">
                        <span class="supplyment-nepal"><?php echo htmlspecialchars($orgName); ?></span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="frame-1f">
                <span class="incorrect-email-password"></span>
              </div>
            </div>
            <button class="frame-20">
              <span class="update-details">Update Details</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="../myjs/eventHandling.js"></script>
</body>

</html>