<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Helvetica:wght@400;700&display=swap" />
    <link rel="stylesheet" href="index.css" />
    <link rel="stylesheet" href="../home/nav.css" />

  </head>
  <body>
    <?php include "../home/nav.php" ?>
    <div class="main-container">
      <div class="frame-9">
        <div class="frame-a">
          <div class="arrow-down-b"><div class="vector-c"></div></div>
          <span class="invoice-created"
            >Invoice #1234 has Created Successfuly </span
          ><span class="thank-you"
            >Thank you for invoicing with us, you can edit and download the
            invoice from my invoices section where you can find various option
            to make changes within your invoices</span
          >
          <div class="frame-d">
            <button class="button-e" id="invoiceTo">
              <div class="frame-f">
                <span class="go-to-history">Go to History</span>
              </div>
            </button>
          </div>
        </div>
      </div>
    </div>
<script src="../myjs/eventHandling.js"></script>
  </body>
</html>
